[package]
name = "dbichart"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
charming = { version = "0.6.0", features = ["ssr"] }
clap = { version = "4.5.51", features = ["derive"] }
postgres = "0.19.12"
